# Use a Node.js image as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Expose the port that the Vue.js application runs on
EXPOSE 8080

# Command to start the application
CMD ["npm", "run", "serve"]

#docker build zain0456/nodeapp:frontend .
#docker container run -d -p 8080:8080 zain0456/nodeapp:frontend